### ISSUE TITLE
Detect Intel vs ARM

### ISSUE THREAD

**Issue by jstaubr** [AsahiLinux/macvdmtool#4]
Hi,

thank you for this amazing tool. I'm trying to create a script around it to be able to have some kind of reinstall station that would detect if a macbook is connected and then install the latest ipsw.
I have it kinda worked out but I want to be able to detect an Intel mac. Do you think it could be possible to implement?

Thanks!

**Comment by marcan** [comment]
It should at least be possible to pick up on differences between Intel and ARM machines based on vendor command responses, but I think you might be able to get a more accurate answer via some product ID thing. I'd suggest looking at the TI programming manual for the TPS6598x and seeing if there is any command or register to get the VID/PID of the remote device.

**Comment by jstaubr** [comment]
Thank you I will try to look at it. In the meantime I found a workaround by looking if it behaves like an M1 mac and disregarding everything else.

**Comment by Ran-Xing** [comment]
@marcan Can I use this tool to boot the Inter device to DFU mode?

I have been using it to solve the problem of M1 brushing, and I hope Intel machines can support it as soon as possible.
